// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKjb4oafs3YHEh_JYJpiAjUrDjxJwt7s',
    appId: '1:374700059859:web:654f6d72c35a9dd188b826',
    messagingSenderId: '374700059859',
    projectId: 'smgi-d9f66',
    authDomain: 'smgi-d9f66.firebaseapp.com',
    storageBucket: 'smgi-d9f66.appspot.com',
    measurementId: 'G-LLXE83H2MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEH-m8KQqVkBbnteekY8QBe5BiqMG8p3g',
    appId: '1:374700059859:android:a3e663ec30dbb30188b826',
    messagingSenderId: '374700059859',
    projectId: 'smgi-d9f66',
    storageBucket: 'smgi-d9f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrzVnP0zQzRPHp4TJEAUsnw2gyYG2s_Ro',
    appId: '1:374700059859:ios:f433af9b09a4012188b826',
    messagingSenderId: '374700059859',
    projectId: 'smgi-d9f66',
    storageBucket: 'smgi-d9f66.appspot.com',
    iosBundleId: 'com.example.smgi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrzVnP0zQzRPHp4TJEAUsnw2gyYG2s_Ro',
    appId: '1:374700059859:ios:cbe4f6402e27127988b826',
    messagingSenderId: '374700059859',
    projectId: 'smgi-d9f66',
    storageBucket: 'smgi-d9f66.appspot.com',
    iosBundleId: 'com.example.smgi.RunnerTests',
  );
}
